name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"

          # Add the Hugging Face remote (with token authentication)
          git remote add space https://bharath0982:${HF_TOKEN}@huggingface.co/spaces/bharath0982/code_generation

          # Force push your main branch to the Hugging Face Space
          git push space main --force
